[package]
name = "can_tool"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.31.0"
egui = "0.31.0"
flume = "0.11.1"
fmt = "0.1.0"
fs = "0.0.5"
io = "0.0.2"
libloading = "0.8.6"
rfd = "0.15.2"
serde = { version= "1.0.218", features = ["derive"] }
serde_yaml = "0.9.34"
